### ISSUE TITLE
Will you release occupancy gt with higher resolution?

### ISSUE THREAD

**Issue by LMerCy** [OpenDriveLab/OccNet#1]
It seems you have occ gt with voxel size of 0.25m , will you release it?
![image](https://github.com/OpenDriveLab/OccNet/assets/13573827/31b47862-c0f9-412e-a909-694b84ddc7d0)

**Comment by ChonghaoSima** [comment]
Yes, gt label with more voxel size will be released later.

**Comment by LMerCy** [comment]
> Yes, gt label with more voxel size will be released later.

I'm curious what is the samllest voxel size you can achieve?

**Comment by ChonghaoSima** [comment]
> > Yes, gt label with more voxel size will be released later.
> 
> I'm curious what is the samllest voxel size you can achieve?

So far we have tried 0.25.
