### ISSUE TITLE
maybe cascade voxel decoder is not necessary?

### ISSUE THREAD

**Issue by lubinBoooos** [OpenDriveLab/OccNet#11]
After reading the paper of _Scene as Occupancy_ I am troubled by the effectiveness of cascade voxel decoder. When I come out to read the code OCCNET, I cannot find the  implementation of cascade voxel decoder, perhaps the decoder is not necessary ?

**Comment by tongwwt** [comment]
The cascade voxel decoder is implemented in the code. Please refer to https://github.com/OpenDriveLab/OccNet/blob/HEAD/projects/mmdet3d_plugin/bevformer/modules/hybrid_transformer.py#L25-L26
