### ISSUE TITLE
Question about 'occ_invalid_path'?

### ISSUE THREAD

**Issue by revisitq** [OpenDriveLab/OccNet#12]
Thanks for sharing the excellent work! The provided mask storied in 'occ_invalid_path' seems to be incorrect. In your code, '1' means a voxel can be observed in camera view and '0' means not. I use the following code to load the data:
```python
voxel_num = 200 * 200 *16
voxel_size = [16, 200, 200]
# load data
occ_path = "xxx/000_occ.npy"
occ_invalid_path = "xxx/000_occ_invalid.npy"
occ_sparse = np.load(occ_path)
mask_sparse = np.load(occ_invalid_path)
# gather data
occ = np.zeros(voxel_num)
mask = np.ones(voxel_num)
occ[occ_sparse[:, 0]] = occ_sparse[:, 1] + 1
mask[mask_sparse] = 0
occ = occ.reshape(*voxel_size).transpose(2, 1, 0)
mask = mask.reshape(*voxel_size).transpose(2, 1, 0).astype(np.bool)
# validate the mask
occupied_voxel_num = (occ!=0).sum()
camera_occupied_voxel_num = (occ[mask]!=0).sum()
print(f'occupied voxel num :{occupied_voxel_num}')
print(f'camera occupied voxel num :{camera_occupied_voxel_num}')
```
I got outputs as follows:
```python
occupied voxel num : 62363
camera occupied voxel num : 62363
```
That's means all the voxels can be observed in camera view and seems to be something wrong with mask in 'occ_invalid_path'. And I also visualize the `mask`:
<img width="917" alt="Screenshot 2023-08-25 at 17 04 19" src="https://github.com/OpenDriveLab/OccNet/assets/68363091/6aa8dd5e-55d9-47c3-af37-3d8acb33dee8">
I really want to know is the `mask` provided in the OpenOcc dataset correct?

**Comment by tongwwt** [comment]
Your output is right. The occ and mask have no overlap in the OpenOcc dataset. The mask is provided to filter the invalid region in the 3D space when evaluating the model performance.

**Comment by revisitq** [comment]
Thanks. Is that means the all the voxel labels can be seen by the camera? Because they are all valid. What's the definition of ‘invalid region in the 3D space‘？
