### ISSUE TITLE
Question about the result about other SOTA methods in the paper?

### ISSUE THREAD

**Issue by YuanxianH** [OpenDriveLab/OccNet#15]
Hi! Thank you for your awesome contribution. 

I notice you compared your method with other SOTA methods (BEVDet/BEVDepth/TPVFormer...) in the Table 3 of the paper. However, the repos of these methods do not provide their implement in OpenOcc dataset. Did you reproduce them in OpenOcc dataset. If so, any configs or code could provide?

**Comment by zhanghm1995** [comment]
I also want to ask this question, since the repo seems to only offer the BEVFormer method, how to obtain the performances of other SOTA methods?

And why the BEVFormer performances are not listed in Table 3?

**Comment by tongwwt** [comment]
1. For other SOTA methods (BEVDet/BEVDepth/BEVDet4D), we just use their repo and replace the detection head as our occupancy head for the occupancy prediction task in our  OpenOcc dataset.
2. For the TPVFormer, we use their repo and our OpenOcc dataset.
3. The BEVFormer performance is implemented as BEVNet in our paper and you can refer to table 14.

**Comment by YuanxianH** [comment]
Thank you for your patient reply.
