### ISSUE TITLE
Question about Generating High-quality Annotation

### ISSUE THREAD

**Issue by LucasYang567** [OpenDriveLab/OccNet#21]
Hello,

The annotated voxel with **unlabeled LiDAR points** from intermediate frame based on the surrounding labeled voxels to further improve the data density.

In this way, the data density can be improved, but it is bound to produce additional errors, especially the shadow caused by **dynamic objects**, how to solve this problem

**Comment by tongwwt** [comment]
Yes, the error can be produced owing to the accumulation of intermediate frame. In general, the data quality is dependent on the calibration of the sensor and annotation of 3D box. We only slightly postprocess the data. We did not process the shadow caused by the dynamic objects.

**Comment by LucasYang567** [comment]
> Yes, the error can be produced owing to the accumulation of intermediate frame. In general, the data quality is dependent on the calibration of the sensor and annotation of 3D box. We only slightly postprocess the data. We did not process the shadow caused by the dynamic objects.

Thanks!
