### ISSUE TITLE
Question about the openocc dataset

### ISSUE THREAD

**Issue by aoyanl** [OpenDriveLab/OccNet#3]
Hi， I wonder the relationship between the dataset  published in cvpr2023-challenge repository and the openocc dataset in this repository. I see the voxel size and range of theirs is different，but you put the leaderboard of CVPR in your README.

**Comment by ChonghaoSima** [comment]
We choose different voxel size and range in the CVPR challenge to be more user-friendly.

Best
Chonghao Sima
________________________________
From: aoyanl ***@***.***>
Sent: Thursday, June 8, 2023 5:33:52 PM
To: OpenDriveLab/OccNet ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [OpenDriveLab/OccNet] Question about the openocc dataset (Issue #3)

---- External Email: Use caution with attachments, links, or sharing data ----


Hi， I wonder the relationship between the dataset published in cvpr2023-challenge repository and the openocc dataset in this repository. I see the voxel size and range of theirs is different，but you put the leaderboard of CVPR in your README.

**Comment by aoyanl** [comment]
> 

Thanks！ Another question is that I see that the paper Occ3D also introduces this dataset ，is it also your work？

**Comment by ChonghaoSima** [comment]
No, that is the work from the Tsinghua MARS Lab. We collaborated with them on the CVPR occupancy challenge.

Best
Chonghao Sima
________________________________
