### ISSUE TITLE
'python setup.py install' error

### ISSUE THREAD

**Issue by githigher** [OpenDriveLab/OccNet#32]
When I switched to the mmdet directory and executed the ' python setup.py install ' command, the following error occurred:

RuntimeError: Scikit-learn requires Python 3.9 or later. The current Python version is 3.8.18 installed in /home/fky/.conda/envs/open-mmlab/bin/python.

**Comment by Valerianding** [comment]
> When I switched to the mmdet directory and executed the ' python setup.py install ' command, the following error occurred:
> 
> RuntimeError: Scikit-learn requires Python 3.9 or later. The current Python version is 3.8.18 installed in /home/fky/.conda/envs/open-mmlab/bin/python.

Hi there

**Comment by Valerianding** [comment]
> When I switched to the mmdet directory and executed the ' python setup.py install ' command, the following error occurred:
> 
> RuntimeError: Scikit-learn requires Python 3.9 or later. The current Python version is 3.8.18 installed in /home/fky/.conda/envs/open-mmlab/bin/python.

Anyone encountered This problem could go to BEVformer issues for help

**Comment by Valerianding** [comment]
> When I switched to the mmdet directory and executed the ' python setup.py install ' command, the following error occurred:
> 
> RuntimeError: Scikit-learn requires Python 3.9 or later. The current Python version is 3.8.18 installed in /home/fky/.conda/envs/open-mmlab/bin/python.

Hi i wonder if you succeed in running the test script. I got a problem issues33(https://github.com/OpenDriveLab/OccNet/issues/33)
