### ISSUE TITLE
Submission for challenge2024 meets erros.

### ISSUE THREAD

**Issue by hanzifan** [OpenDriveLab/OccNet#35]
I used to run the baseline code and got the submission.gz file. Then I submitted this file for the challenge20204 but met this error.
![1713334218987](https://github.com/OpenDriveLab/OccNet/assets/43206681/5bd2d18b-9ea3-442f-b45b-095d3754744e)
And here's my model card which was created for the submission.
![1713334523432](https://github.com/OpenDriveLab/OccNet/assets/43206681/b1d8e9b3-872c-4e5a-95b9-2093ebdba174)

**Comment by Kjxxxxxx** [comment]
创建好了模型，也登录了
<img width="341" alt="屏幕截图 2024-04-17 150938" src="https://github.com/OpenDriveLab/OccNet/assets/100982227/c08e1609-682b-40d7-8631-0a3882713d3e">

为什么还是无效的命令nie捏

**Comment by iiiiiikou** [comment]
我的sub有2个G，这个是不是不太全

**Comment by hanzifan** [comment]
> 我的sub有2个G，这个是不是不太全

啊这样吗，可是我那个就是跑的这个命令啊
```
./tools/dist_test.sh projects/configs/bevformer/bevformer_base_occ_test.py work_dirs/bevformer_base_occ/epoch_24.pth 8 --format-only --eval-options 'submission_prefix=./occ_submission'
```

**Comment by sephyli** [comment]
This is a server-side error and we are looking into it. We will back soon.

**Comment by hanzifan** [comment]
> This is a server-side error and we are looking into it. We will back soon.

What about this issue now?

**Comment by hanzifan** [comment]
> > This is a server-side error and we are looking into it. We will back soon.
> 
> What about this issue now?

My fault, it works now.
