### ISSUE TITLE
Meaning on Results Metrics

### ISSUE THREAD

**Issue by russellyq** [OpenDriveLab/OccNet#49]
Hi,

Thanks for your great work.

However, as I re-implement the baseline and get the results, I see some mismatch between your results and the paper`s results ? 

How should I interpret the results?
baseline:
+----------------------+-------+-------+-------+-------+
|     Class Names      | IoU@1 | IoU@2 | IoU@4 |  AVE  |
+----------------------+-------+-------+-------+-------+
|         car          | 0.542 | 0.616 | 0.638 | 3.009 |
|        truck         | 0.380 | 0.475 | 0.515 | 1.834 |
|       trailer        | 0.199 | 0.268 | 0.331 | 3.569 |
|         bus          | 0.477 | 0.592 | 0.649 | 3.386 |
| construction_vehicle | 0.129 | 0.206 | 0.233 | 0.082 |
|       bicycle        | 0.000 | 0.000 | 0.000 | 0.062 |
|      motorcycle      | 0.134 | 0.149 | 0.155 | 3.463 |
|      pedestrian      | 0.238 | 0.275 | 0.284 | 0.968 |
|     traffic_cone     | 0.173 | 0.184 | 0.187 |  nan  |
|       barrier        | 0.359 | 0.401 | 0.418 |  nan  |
|  driveable_surface   | 0.468 | 0.564 | 0.670 |  nan  |
|      other_flat      | 0.237 | 0.284 | 0.319 |  nan  |
|       sidewalk       | 0.237 | 0.281 | 0.323 |  nan  |
|       terrain        | 0.226 | 0.288 | 0.345 |  nan  |
|       manmade        | 0.295 | 0.352 | 0.390 |  nan  |
|      vegetation      | 0.170 | 0.258 | 0.330 |  nan  |
+----------------------+-------+-------+-------+-------+
|         MEAN         | 0.267 | 0.325 | 0.362 | 2.047 |
+----------------------+-------+-------+-------+-------+
 --- Occ score: 0.2858669209909098

**Comment by sephyli** [comment]
If you want to reproduce the result of "Scene as Occupancy", please checkout the repo to `occnet` branch. The default branch is for the Occupancy and Flow prediction challenge.

**Comment by russellyq** [comment]
well noted !

Thanks for your quick answer.
