### ISSUE TITLE
Question about difference in point cloud range

### ISSUE THREAD

**Issue by haiphamcse** [OpenDriveLab/OccNet#5]
Hi there, loved your work. I want to ask about your choice of pc range: [-50m, -50m, -5m, 50m, 50m, 3m]. Compared to the CVPR workshop 2023 (https://github.com/CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction), which has the range [-40m, -40m, -1m, 40m, 40m, 5.4m], why don't the dataset follow the same range? Thank you.

**Comment by ChonghaoSima** [comment]
please refer to #3

**Comment by haiphamcse** [comment]
Hi there, I have read the comments. However I want to follow up with do you provide a code for transforming your coordinate system with the corresponding pc_range to the CVPRW2023 coordinate (IMU) and pc_range? Thanks

**Comment by ChonghaoSima** [comment]
Yes, that’s on our TODO list. Please stay tuned.

Best
Chonghao Sima
________________________________

**Comment by wanghanhan** [comment]
> Yes, that’s on our TODO list. Please stay tuned.
> 
> Best
> Chonghao Sima
> […](#)

Hello, is there any updates about this issue (providing codes for transforming the pc_range and resolution)? Thanks
