### ISSUE TITLE
Question about the motivation of OccNet dataset

### ISSUE THREAD

**Issue by haiphamcse** [OpenDriveLab/OccNet#6]
Hi there, firstly thank you to your team for contributing significant work for the community.
I want to ask about the motivation for your dataset, compared to others such as Occ3D[1], OpenOccupancy[2]. I see that your dataset only annotate 16 classes + 1 unknown class. As i'm aware the unknown class contains free space and some long tail classes in nuscene-lidarseg (animals, firetruck, etc). Why do your team choose this approach compared to seperating long tail classes to general objects (GO) and a different free class.
Best regards.
[1] Occ3D: A Large-Scale 3D Occupancy Prediction Benchmark for Autonomous Driving
[2] OpenOccupancy: A Large Scale Benchmark for Surrounding Semantic Occupancy Perception

**Comment by ChonghaoSima** [comment]
We leave the unknown class to be discussed in detail in the future, in the form of open-vocabulary occupancy.
