### ISSUE TITLE
occ_invalid_path具体表示的是什么?

### ISSUE THREAD

**Issue by dywu98** [OpenDriveLab/OccNet#9]
请问occ_invalid_path 是不是更类似于 semantickitti数据集里的 invalid标注? 跟semantic kitti的occluded标注不一样

**Comment by zhouyunsong** [comment]
Thanks for your attention. The 'invalid' annotation of OccNet filters out the occupancy outside of the camera view and only keeps the part within the camera's imaging field of view, rather than removing the occluded and invisible parts.

**Comment by dywu98** [comment]
感谢您的回复，按照您对说法，那这里的 visblemask是不等同于 cvpr2023challenge中的visible mask的对吧？

**Comment by zhouyunsong** [comment]
Basically the same.

**Comment by ChonghaoSima** [comment]
And please use English for further conversation.
